---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.podinfod: semver:1.5.x
  name: podinfo
  namespace: demo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: podinfod
      containers:
      - image: stefanprodan/podinfo:3301f6f
        name: podinfod
